### ISSUE TITLE
Allow content-type filtering in `sema.discovery`

### ISSUE THREAD

**Issue by cedricdcc** [vliz-be-opsci/py-sema#30]
Implement a feature to provide a list of content-types to be loaded.

**Comment by cedricdcc** [comment]
Links to #29

**Comment by marc-portier** [comment]
This special feature originates from existing services (like orcid.org) producing less/more triples in various conneg variants (the json-ld does not 1-1 match the ttl)

So the idea would be that when using the main discovery service one could specify a list of content-types it should *all* try and get to combine a fuller set of triples into the Graph it builds as a response.

Note this list is indicating 'Accept' headers to call for - it in no way guarantees those will also be delivered - reading the response 'content-type' remains important

We might also consider having similar report for conneg-by-profile headers in the future - so maybe this might turn out to be addressed by (1) providing a list of request-headers to be applied in distinct requests and (2) some easy way to produce such lists from cartesian product of mimetipes, profiles, and why not other stuff?
