### ISSUE TITLE
Enhance HTTP Header Parsing in Tests with cgi.parse_header()

### ISSUE THREAD

**Issue by cedricdcc** [vliz-be-opsci/py-sema#65]
Currently, our tests rely on a custom implementation for parsing HTTP headers. This approach, while functional, may lead to unintended (though unlikely) stray matches due to the manual parsing logic. To improve the accuracy and reliability of our tests, we should utilize the cgi.parse_header() function from Python's standard library, which is designed for proper parsing of HTTP headers.

**Comment by marc-portier** [comment]
one clear case is at https://github.com/vliz-be-opsci/py-sema/blob/46f24a2b5853afe88389eb9f8da1f84635dd8a7d/sema/discovery/url_to_graph.py#L99
