### ISSUE TITLE
 Reduce Dependency on External Services by Using Local HTTP Server for Tests

### ISSUE THREAD

**Issue by cedricdcc** [vliz-be-opsci/py-sema#66]
Our current test suite heavily depends on external services, which can lead to instability and unpredictability in our tests due to potential changes in the files.To improve the reliability and control over our test outcomes, we should implement a local HTTP server that can be spun up during tests. This will allow us to mock external services, providing consistent and predictable responses.

## Proposed solution

* Integrate a lightweight HTTP server within our test framework. Libraries like http.server (built-in), Flask, or pytest-httpserver can be used for this purpose.

* Configure the local server to simulate the behavior of external services that our tests depend on.
* Create mock endpoints with predefined responses to cover various test scenarios.

**Comment by marc-portier** [comment]
inspiration -- use the http server we introduced in https://github.com/vliz-be-opsci/py-trav-harv/blob/main/tests/conftest.py

**Comment by marc-portier** [comment]
note that also the current discovery test already has live URL dependencies to be taken into account for this.

https://github.com/vliz-be-opsci/py-sema/blob/main/tests/discovery/test_url_to_graph.py

**Comment by cedricdcc** [comment]
There should already by an implmentation that would allow the usgae of valid domains that the check_valid_uri does not flag as invalid.
See https://github.com/vliz-be-opsci/py-sema/pull/124#issuecomment-2401768526
