### ISSUE TITLE
refactor sema.subyt.main to use service interface

### ISSUE THREAD

**Issue by cedricdcc** [vliz-be-opsci/py-sema#82]
Interface right now uses service with function arguments.

This should be converted to be able to use string arguments so that this can be cli tested.

sema.syncfs.__main__.py should be taken as an example for this approach.

tasks:

- [ ] : refactor service.py to use all the different functions that are now defined in __main__.py
- [ ] : add tests for main function

**Comment by marc-portier** [comment]
should follow also the new strategy in sema.commons.service
